vultr:
  api_base: "https://api.vultr.com/v2"

ssh:
  user: "ubuntu"
  keyfile: ""    # 留空表示使用 ssh-agent

remote:
  base_dir: "/home/ubuntu/vultragentsvc"
  project_dir: "/home/ubuntu/asr_program"
  inputs_dir: "/home/ubuntu/asr_program/audio"
  outputs_dir: "/home/ubuntu/asr_program/output"
  models_dir: "/home/ubuntu/.cache/asrprogram/models"
  log_file: "/home/ubuntu/vultragentsvc/run.log"
  tmux_session: "vultragentsvc"
  bootstrap_tmp_path: "/tmp/vultragentsvc_bootstrap.sh"  # 上传脚本的临时存放路径

git:
  repo_url: "https://github.com/yourname/your-asr-repo.git"
  branch: "main"
  prefer_https: true         # 公共仓库推荐启用，私有仓库可设为 false 使用 SSH
  local_repo_dir: ""        # 指向本地 ASR 仓库的路径，部署前会自动 git pull

asr:
  entry: "asr_quickstart.py"
  args:
    input_dir: "/home/ubuntu/asr_program/audio"
    output_dir: "/home/ubuntu/asr_program/output"
    models_dir: "/home/ubuntu/.cache/asrprogram/models"
    model: "large-v2"
    # flag_aliases:
    #   output_dir: ["--output", "--out-dir"]  # 可使用列表或以空格/逗号分隔的字符串
    extra: []                 # 追加自定义参数数组，例如 ["--lang", "zh", "--threads", "8"]
  python_bin: "python3"       # 允许切换到虚拟环境中的 python 可执行文件
  non_interactive: true       # 若入口需要交互则改为 false，并在 README 中提示改造方案

transfer:
  upload_local_dir: "./materials"   # 本地待上传的素材目录
  download_glob: "*.json"
  results_root: "./results"
  retries: 3
  retry_backoff_sec: 3
  verify_manifest: true
  manifest_name: "_manifest.txt"

cleanup:
  remove_remote_outputs: false
  rotate_remote_logs: true
  keep_log_backups: 5

logging:
  local_root: "./logs"          # 本地日志根目录
  filename: "run.log"           # 本地保存的文件名（每次会放入带实例与时间戳的目录）
  mirror_on_view: true           # 进入“实时查看”时，是否自动镜像到本地
  mirror_interval_sec: 3         # 实时查看时，附加的周期性 rsync 间隔（秒）

huggingface:
  token: ""              # 运行时从本地 config.yaml 注入，仓库中保持留空
  persist_login: true     # 是否使用 huggingface-cli 进行持久化登录
  set_git_credential: true
  hf_home: "/home/ubuntu/.cache/huggingface"
