vultr:
  api_base: "https://api.vultr.com/v2"

ssh:
  user: "ubuntu"
  keyfile: ""    # 留空表示使用 ssh-agent

remote:
  base_dir: "/home/ubuntu/vultragentsvc"
  project_dir: "/home/ubuntu/asr_program"
  inputs_dir: "/home/ubuntu/asr_inputs"
  outputs_dir: "/home/ubuntu/asr_outputs"
  models_dir: "/home/ubuntu/.cache/asrprogram/models"
  log_file: "/home/ubuntu/vultragentsvc/run.log"
  tmux_session: "vultragentsvc"
  bootstrap_tmp_path: "/tmp/vultragentsvc_bootstrap.sh"  # 上传脚本的临时存放路径

git:
  repo_url: "git@github.com:yourname/your-asr-repo.git"
  branch: "main"

asr:
  entry: "asr_quickstart.py"
  args:
    input_dir: "/home/ubuntu/asr_inputs"
    output_dir: "/home/ubuntu/asr_outputs"
    models_dir: "/home/ubuntu/.cache/asrprogram/models"
    model: "large-v3"
    extra: []

transfer:
  download_glob: "*.json"

huggingface:
  token: ""              # 运行时从本地 config.yaml 注入，仓库中保持留空
  persist_login: true     # 是否使用 huggingface-cli 进行持久化登录
  set_git_credential: true
  hf_home: "/home/ubuntu/.cache/huggingface"
